# Generated by Django 4.2.7 on 2023-11-12 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('name', models.CharField(default='name', max_length=100)),
                ('email', models.EmailField(default='email', max_length=100, unique=True)),
                ('password', models.CharField(default='password', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
