# Generated by Django 4.2.7 on 2023-11-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dentist_patient_dentist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dentist',
        ),
    ]
