# Generated by Django 4.2.7 on 2023-12-03 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patienttoken_dentisttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentisttoken',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patienttoken',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
