version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: UserDB
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: True
      SECRET_KEY: 6b1f53f85e4d136b296fb8542285e954
    extra_hosts:
     - "host.docker.internal:host-gateway"
    networks:
      - userservice


  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=UserDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - userservice

volumes:
  postgres_data:

networks:
  userservice:
    driver: bridge